### ISSUE TITLE
Add Flyway migration support

### ISSUE THREAD

**Issue by Maxitet** [TomSuworof/briene#5]
Initial structure of DB should be added as SQL script and will be applied by Flyway at runtime.
Docs: https://flywaydb.org/documentation/getstarted/firststeps/maven
Default directory is: src/main/resources/db/migration/

**Comment by TomSuworof** [comment]
Here is how to use Flyway with profiles: [StackOverflow](https://stackoverflow.com/questions/59532496/how-to-set-flyway-migration-file-location-using-spring-profiles)
